cloud:
  aws:
    credentials:
      accessKey: # S3 accessKey
      secretKey: # S3 secretKey
    region:
      static:
        ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: moyeo-skillstack
      #dir: #S3 디렉토리 이름