spring:
  application:
    name: moyeo-study
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config: # 기존 profile include 방식에서 부트2.4에서는 멍청한 방향으로 변경되었기 때문에 레거시 설정 사용
    use-legacy-processing: true
  profiles:
    include:
      - oauth
      - aws

logging:
  level:
    com:
      justcodeit:
        moyeo:
          study: debug

moyeo:
  auth:
    header:
      scheme: X-MOYEO-AUTH-TOKEN
    redirect:
      whenLoginSuccess:
        uri: '/for_test_uri' #임시 url, 존재 x
  jwt:
    secret: ObN1YjTovA4khj07ox/L5OUVx5g55KOY272DCU2ARtk=
    expiryMills: 3600000

springdoc:
  default-consumes-media-type: text/yaml
